/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function plus100(input: number): number
export function fibonacci(input: number): number
export function main(): void
