/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Cli {
  command: string
  args: Array<string>
}
export function sum(a: number, b: number): number
export function main(options: Cli): void
